### ISSUE TITLE
expose babel config

### ISSUE THREAD

**Issue by bboydflo** [webextension-toolbox/webextension-toolbox#114]
## Expected Behavior
I would like to be able to configure `babel-loader`. Today the boilerplate this project offers is tightly coupled to react (includes react specific config for babel-loader). It would be nice to have an easier way to configure this (maybe do babel config in package.json?). 

## Current Behavior
No easy way to configure babel. `webextension-toolbox` is tightly coupled to `react`

## Context
I would like to use other libraries with JSX like `preact`, therefore I need to be able to change babel-loader config.

## Your Environment
Not relevant

**Comment by bboydflo** [comment]
I actually found a way to customize `babel-loader` in `webextension-toolbox-config.js` using something like this:
```js
config.module.rules.push({
  test: /\.js$/,
  use: [
    {
      loader: 'babel-loader',
      options: {
        babelrc: true,
        extends: join(__dirname + '/.babelrc'),
        cacheDirectory: true,
        envName: dev ? 'development' : 'production'
      }
    }
  ]
})
``` 
and put the relevant babel config in `.babelrc`

**Comment by CanRau** [comment]
Based on your code @bboydflo and the `bookmarkit` example I noticed the possibility to provide a custom config to override webpack without monkey patching
Code in https://github.com/webextension-toolbox/webextension-toolbox/issues/174#issuecomment-535753367

**Comment by tm1000** [comment]
#174 will solve this. In #143 we removed the need for React.
