### ISSUE TITLE
Native VueJS support?

### ISSUE THREAD

**Issue by NuroDev** [webextension-toolbox/webextension-toolbox#125]
### A nice quality of life improvement
> I can see that currently there is native support for React which is great! 👌 
Is there any plans to add native VueJS support in the future? I know it can be done already by using a custom `webextension-toolbox-config.js` file, but having native support in the future would be nice 😄

**Comment by pbek** [comment]
webextension-toolbox is great and I love it! Is there any way to get VueJS running with it? I haven't figured one out so far. I wanted to port https://github.com/qownnotes/web-companion/ to VueJS...

**Comment by NuroDev** [comment]
@pbek I'm currently working on a project and have managed to get it working for now but it has a few issues. Mainly that Vue dev tools does not work and that due to the preset webpack copy ignore setup, it will still copy over the `.vue` files even though they are not needed post build.

Have a look here for how I did it 😄 
[github.com/tdemapp/tdem](https://github.com/tdemapp/tdem)

**Comment by pbek** [comment]
Ah, thank you! So you are working with ` "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"`, I didn't dare to do that yet. I will try that out today! Thanks a lot so far!

**Comment by pbek** [comment]
@NuroDev your extension is really a great help for me getting going with VueJS, thank you very much!

**Comment by balcsida** [comment]
Hi @NuroDev, @pbek,

Thank you for bringing up this idea.
While I don't have deep experience with Vue.js, a colleague of mine was able to use it with WebExtension Toolbox.
I will ask him how he did it.

Kind regards,
@balcsida

**Comment by pbek** [comment]
I now released https://github.com/qownnotes/web-companion/ for Chrome and Firefox, thank you again @NuroDev for your help and @balcsida for your great tools!

**Comment by balcsida** [comment]
Hi @pbek,

I'm happy to hear that you were able to release your extension.
I also would like to mention that these tools were developed by @HaNdTriX, I'm just trying to maintain it in my free time. So I would forward your kind words to him. :slightly_smiling_face: 

Cheers,
@balcsida

**Comment by pbek** [comment]
Thank you for both your work! Extra free time work is always hard. I can sing a song about it at https://github.com/pbek/QOwnNotes :laughing: But kind words are at least a good motivation to keep us going.

**Comment by tm1000** [comment]
Fixed from #143
