### ISSUE TITLE
Expose copy files ignore

### ISSUE THREAD

**Issue by NuroDev** [webextension-toolbox/webextension-toolbox#126]
Currently, the webpack copy plugin has a pre-defined set of file extensions to ignore. Exposing this would be super helpful to let people blacklist file types from being copied over that they do not want 👍 
Or an alternative is an option to toggle/disable copying all other files in your `app` directory to the build directory 😄

**Comment by NuroDev** [comment]
No problem. I actually found a solution to the issue. In one of your other issues, #93 to be exact, a user actually shows how to override the default `copyIgnore` object with your own.
[github.com/webextension-toolbox/webextension-toolbox/issues/93](https://github.com/webextension-toolbox/webextension-toolbox/issues/93#issuecomment-422022157).

I can use this to disable the file extensions I need 😄

**Comment by balcsida** [comment]
Hi @NuroDev,

I'm glad that this matter is resolved for you.
I raised the priority on #93 in order to have that documented properly.

Kind regards,
@balcsida
