### ISSUE TITLE
cannot pass vendorVersion option to webextension-toolbox

### ISSUE THREAD

**Issue by bboydflo** [webextension-toolbox/webextension-toolbox#134]
## Expected Behavior
when calling this package like this: `webextension-toolbox dev chrome --vendorVersion=71` I expect the vendorVersion to be passed further to `src/compile` script. I think or it seems that it doesn't

I did a bit of research and wrote a bit more [here](https://github.com/webextension-toolbox/webextension-toolbox/commit/847bbf29fb663dada0996fcc4d1cea64be712510#diff-0180f431911bb2b7615af9c8f1dbae45)

Passing `vendorVersion` has an influence on the `babel-loader` more specifically on `babel/preset-env` and how the code gets transpiled. This is a core feature and doesn't work correctly in my opinion.

**Comment by HaNdTriX** [comment]
Sorry for my late response. I am currently working on some other projects and didn't had the time to track this Repository. You are totally right. 

I've just created a PR to fix this.
