### ISSUE TITLE
FireFox extension signing

### ISSUE THREAD

**Issue by ilan-toluna** [webextension-toolbox/webextension-toolbox#148]
Hi
I am aware that your documentation states that if extension signing is a requirement then you recommend using web-ext.

Can you please provide best solution to sign the FF extension while still using your toolbox?

**Comment by balcsida** [comment]
Hi @ilan-toluna,

Unfortunately, it is not possible to sign extensions with WebExtension Toolbox, you need to use web-ext to do this for Firefox.
If we would build this functionality in, it would still rely on web-ext, but that would mean another dependency that someone else wouldn't use ever.

Kind regards,
@balcsida
