### ISSUE TITLE
manifest.json enviroment keys

### ISSUE THREAD

**Issue by niklv** [webextension-toolbox/webextension-toolbox#158]
Is there anyway to do it?
I want add 
```json
"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
```
to eval source maps in chrome dev console.

But I want to remove this line in production build.

**Comment by balcsida** [comment]
Hi @Niklv,

I don't think it is possible to do this right now, but this sounds like a good feature request.
Do you have any other keys or scenarios where this environment specification would come handy?

Kind regards,
@balcsida

**Comment by sigmike** [comment]
I also would like something similar. I have some variation of an extension and I would like the name and icons of the extension to change based on some environment variables. Right now I just generate a custom `manifest.json` before running dev or build.

**Comment by greatghoul** [comment]
You can do this by replace `manifest.json` content while compiling

`webextension-toolbox-config.js`

```js
const webpack = require('webpack')
const ReplaceInFileWebpackPlugin = require('replace-in-file-webpack-plugin');

module.exports = {
  webpack: (config, { dev, vendor }) => {
    const security = dev
      ? `,"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"`
      : ''

    config.plugins.push(new ReplaceInFileWebpackPlugin([
      {
        dir: `dist/${vendor}`,
        files: ['manifest.json'],
        rules: [{
          search: '<manifest-security>',
          replace: security
        }]
      }
    ]))

    return config
  }
}
```

then in your manifest.json

```json
{
  ...
  "permissions": [
    "storage",
    "notifications"
  ]
  <manifest-security>
}
```

**Comment by greatghoul** [comment]
> I don't think it is possible to do this right now, but this sounds like a good feature request.
Do you have any other keys or scenarios where this environment specification would come handy?

@balcsida For example you have your extension to communicate the api server, but api used in development is a test server, while published, it should be production server. You need to add different url permissions in manifest.json

**Comment by tm1000** [comment]
This is now in 5.0.0
