### ISSUE TITLE
Add a compile done marker to dev output

### ISSUE THREAD

**Issue by ChaosinaCan** [webextension-toolbox/webextension-toolbox#159]
## Expected Behavior

It would be very helpful to add markers to the `webextension-toolbox dev ...` output to mark the start and end of the output for one compilation, similar to what is done by webpack-cli with the --info-verbosity=verbose option: https://github.com/webpack/webpack-cli/blob/master/bin/cli.js#L274

This would allow for tools that analyze the output of webextension-toolbox to identify when webpack recompiles the extension, and to parse warnings and errors from the latest compilation.

## Current Behavior

Errors and warnings are printed at the end of the output. An external tool cannot know when one compilation is done until the next one starts.

## Steps to Reproduce (for bugs)

1. Create an extension using ts-loader and tslint-loader as described in https://github.com/webextension-toolbox/webextension-toolbox/issues/93#issuecomment-422022157
2. Add a tslint.json to the root of the project:
```json
{
    "extends": "tslint:recommended"
}
```
3. Add a .ts file with some code that tslint will flag. A statement that doesn't end with a semicolon will work.
4. Run `webextension-toolbox dev chrome`.

## Context

I use Visual Studio Code as my IDE, and it can be configured to parse the output of a build task for warnings and errors. When parsing the output of a task that watches for changes and automatically recompiles (such as `webpack --watch` or `webextension-toolbox dev ...`), it needs to match some text at the start and end of each re-compilation to identify the latest output.

See https://github.com/eamodio/vscode-tsl-problem-matcher/blob/master/package.json#L111 for an example configuration to parse the output of `webpack --watch` for warnings from tslint.

For now I have been adding the following plugin to my build:

```js
export class VSCodeOutputWebpackPlugin {
    public apply(compiler) {
        // Match output of https://github.com/webpack/webpack-cli/blob/master/bin/cli.js
        // so that $*-webpack-watch problem matchers work.
        compiler.hooks.done.tap('WebpackInfo', stats => {
            if (stats.hasErrors() || stats.hasWarnings()) {
                console.error(`\nCompilation ${compiler.name} starting…\n`);
                console.error(stats.toString('errors-warnings'));
                console.error(`\nCompilation ${compiler.name} finished\n`);
            }
        });
    }
}
```

This usually works, but it doubles any warnings/errors in the output. It would be nice if WebExtension Toolbox had a verbose option like "webpack --watch --info-verbosity=verbose" or marked the start/end of its output by default.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | 3.0.0       |
| node                    |  12.3.1       |
| OS                      |  Windows 10 build 17763       |
| vscode                     |  1.34.0       |

**Comment by balcsida** [comment]
Hi @ChaosinaCan,

This is an excellent improvement idea!
Unfortunately, I can't see yet when I will have time to implement this. So - if possible - could you please send a Pull Request?

Kind regards,
@balcsida

**Comment by ChaosinaCan** [comment]
I think I've figured out where the code needs to go. Pull request incoming...

**Comment by balcsida** [comment]
Thank you so much for the PR!
