### ISSUE TITLE
WebSocket Connection Failure

### ISSUE THREAD

**Issue by godadada** [webextension-toolbox/webextension-toolbox#164]
built the example bookmarkit extension for chrome and manually loaded to chrome. It shows an error message:

WebSocket connection to 'ws://127.0.0.1:35729/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

## Expected Behavior

no error message

no

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |         |
| node                    |         |
| OS                      |         |
| browser                 |         |
| etc                     |         |

**Comment by godadada** [comment]
the root of the issue may be because ws tries to connect to localhost. here is similar situation with another extension:

https://github.com/livereload/livereload-extensions/pull/35

**Comment by balcsida** [comment]
Hi @godadada,

I'm so sorry this happened.
Could you please share the exact steps you used when this issue happened?

Kind regards,
@balcsida

**Comment by CanRau** [comment]
I'm not sure why it worked before for me and I'm pretty sure (not 100% though) that Brave (Chromium based browser) didn't update yet it seems to be a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1006243
I'm on Chromium: 77.0.3865.90
In Google Chrome Canary v79.0.3924.0 it's working without a problem

Only thing that changed was that I added a `webextension-toolbox-config.js` to customize webpack 🧐which is also used in the bookmarkit example using a different file name though
I tried to comment the changes out but couldn't get it to work again 😢
