### ISSUE TITLE
Add config path argument

### ISSUE THREAD

**Issue by NuroDev** [webextension-toolbox/webextension-toolbox#165]
Would be a nice added CLI option to be able to manually specify the path to your `webextension-toolbox.config.js`. Since that's a bit of a mouthful it would be handy if I could rename it to something like `webext.config.js` or similar and be able to pass something like `--config` or `-c` to specify a config path 😄

**Comment by balcsida** [comment]
Good idea! Thanks for the PR as well, started checking now...

**Comment by balcsida** [comment]
Sorry, I went home to catch some Zs in the end
