### ISSUE TITLE
Support for testing framework (mocha or other?)

### ISSUE THREAD

**Issue by Fedcomp** [webextension-toolbox/webextension-toolbox#176]
webextension-toolbox takes care of running webpack with it's own config so i can't use things like https://github.com/zinserjan/mocha-webpack

It would be cool to have testing frameworks support of some sort.

**Comment by tm1000** [comment]
You can supply a custom webpack config https://github.com/webextension-toolbox/webextension-toolbox#customizing-webpack-config
