### ISSUE TITLE
Sign packages

### ISSUE THREAD

**Issue by carlin-q-scott** [webextension-toolbox/webextension-toolbox#187]
Thank you for making this tool, but I feel like I was misled about the functionality.

## Expected Behavior
I expected the packages to be signed so that I can publish/share them.

## Current Behavior
Packages are just zip archives and still require signing in order to be installed in a browser.

## Context
I started using this tool thinking it would create signed packages. I had little other use for it as I was already using the webextension-polyfill npm package to fill in the browser object and support APIs across browsers. So basically all this tool is doing for me, is avoiding warnings when I have things in my manifest.json that are only supported by certain browsers.

**Comment by tm1000** [comment]
Could use https://github.com/mozilla/sign-addon for firefox.

I dont think any other vendor supports signing (unless I'm mistaken)
