### ISSUE TITLE
contentscript doesn't auto/hot reload

### ISSUE THREAD

**Issue by Dealerpriest** [webextension-toolbox/webextension-toolbox#207]
## Expected Behavior
On save I expect the changes I've made to `contentscript.js` (or whichever file is set as `content_script` in `manifest.json`) to be reflected in the result when the page reloads.

## Current Behavior
The page reloads. But the `contentscript.js` is not running the made changes.

## Steps to Reproduce (for bugs)

1. Generate a webpack project using the Yeoman [generator-web-extension](https://github.com/webextension-toolbox/generator-web-extension)
2. Add the dist/\<vendor\> folder as a temporary extension as described [here](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)
3. cd into project and `npm run dev <vendor>`
4. Try to save changes to `contentscript.js` and see if the changes are represented when the page reloads.

## Context

hot reloading
auto reloading

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |       3.0.0  |
| node                    |     v8.9.4    |
| OS                      |     Win 10    |
| browser                 |    Firefox/Chrome     |

**Comment by Dealerpriest** [comment]
I would be interested in whether this is an actual bug or if it's something wrong with my setup? Are others experiencing the same problem?

**Comment by Dealerpriest** [comment]
@balcsida 
Do you have any thoughts on this?

**Comment by SnidelyWhiplash** [comment]
I'm also experiencing this, at least in Firefox. Chrome seems to work as expected.

**Comment by ThePaavero** [comment]
Same here. Windows 10, Firefox 84.0.

**Comment by tm1000** [comment]
See #82
