### ISSUE TITLE
Add Edge autoreload support

### ISSUE THREAD

**Issue by HaNdTriX** [webextension-toolbox/webextension-toolbox#22]
## Expected Behavior

Autoreload should work in MS-Edge.

## Current Behavior

In MS-Edge websocket connections to `localhost` are blocked by design.

* https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8984919/
* https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging

## Steps to Reproduce (for bugs)

1. Run `webextension-toolbox dev edge`
2. Open background console

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |  1.0.0-beta.6  |
| node                    |  v9.1.0  |
| OS                      |  Windows 10 |
| browser                 | Edge |

## Related Issues

* https://github.com/HaNdTriX/webextension-toolbox/issues/4

**Comment by HaNdTriX** [comment]
Since not even localhost is working properly I am not sure how the bypass this restriction.
I thought about moving over to a polling approach in edge, but that doesn't work either. 🤔

**Comment by balcsida** [comment]
What Windows 10 build are you using for testing?

**Comment by balcsida** [comment]
Also, you can check this flag under `about:flags`
![image](https://user-images.githubusercontent.com/1768446/38366852-5a944112-38e1-11e8-833a-551e68366f90.png)

**Comment by HaNdTriX** [comment]
> What Windows 10 build are you using for testing?

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

> Also, you can check this flag under about:flags

Doesn't change it

**Comment by balcsida** [comment]
I installed the latest version of Windows 10 (1803, Build 17133.1) yesterday and I will try make some tests on the weekend.
If it is still not working, then we can try both native messaging (requires an UWP app)
 or XHR/Fetch.

**Comment by balcsida** [comment]
I did some fiddling around today and found qzind/tray#6
When I disabled "Include all local (intranet) sites not listed in other zones", the WebSocket connection worked like expected
![fix_edge_websocket](https://user-images.githubusercontent.com/1768446/39151474-a0ab6ea6-4745-11e8-8f59-b2aafd101da2.gif)

**Comment by balcsida** [comment]
In short, this registry file should do the trick:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap]
"IntranetName"=dword:00000000
```

**Comment by bboydflo** [comment]
@balcsida  and @HaNdTriX  maybe move these docs to the readme.md?

**Comment by balcsida** [comment]
I was thinking about something more... automatic... but you are right, this should be in the README as well

**Comment by balcsida** [comment]
In the future, we might use something like QZ does (localhost.qz.io) or ask them to allow us to use this domain.

**Comment by balcsida** [comment]
Maybe use [xip.io](http://xip.io/) for this?
```
Name:     127.0.0.1.xip.io
Address:  127.0.0.1
```
