### ISSUE TITLE
Doesn't Edge need to be polyfilled?

### ISSUE THREAD

**Issue by SnidelyWhiplash** [webextension-toolbox/webextension-toolbox#271]
## Expected Behavior

Edge should work out of the box.

## Current Behavior

Edge extension does not work.

## Steps to Reproduce (for bugs)

1. Try to access any APIs via `browser` in either a background or content script
2. Run your extension in Edge
3. You'll get a `browser is not defined` runtime error

## Context

As I understand it, Edge is (recently?) using the chromium APIs, not the Mozilla/standardized ones. As such, accessing any API via `browser` throws an error. I somewhat polyfilled it in my case with a simple `if (typeof browser === 'undefined') browser = chrome` line at the top of my scripts, which works for a lot of APIs since they're similar, but certainly not all of them.

I don't know, but I wonder if it's as simple as adding `edge` to this line here --> https://github.com/webextension-toolbox/webextension-toolbox/blob/master/src/webpack-config.js#L121

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | 3.0.0 |
| node                    | 10.6.0 |
| OS                      | macOS High Sierra (10.13.6) |
| browser                 | Edge for Mac (81.0.416.68) |

**Comment by fapdash** [comment]
@SnidelyWhiplash For now you can add a file named `webextension-toolbox-config.js` at the toplevel of your project:

``` js
// This file is not going through babel transformation.
// So, we write it in vanilla JS
// (But you could use ES2015 features supported by your Node.js version)
const webpack = require("webpack");

module.exports = {
  webpack: (config, { dev, vendor }) => {
    // Perform customizations to webpack config

    // TODO(FAP): can be removed once https://github.com/webextension-toolbox/webextension-toolbox/pull/347 is merged
    // Add webextension polyfill
    if (["edge"].includes(vendor)) {
      config.plugins.push(
        new webpack.ProvidePlugin({
          browser: require.resolve("webextension-polyfill"),
        })
      );

      // The webextension-polyill doesn't work well with webpacks ProvidePlugin.
      // So we need to monkey patch it on the fly
      // More info: https://github.com/mozilla/webextension-polyfill/pull/86
      config.module.rules.push({
        test: /webextension-polyfill[\\/]+dist[\\/]+browser-polyfill\.js$/,
        loader: require.resolve("string-replace-loader"),
        query: {
          search: 'typeof browser === "undefined"',
          replace:
            'typeof window.browser === "undefined" || Object.getPrototypeOf(window.browser) !== Object.prototype',
        },
      });
    }

    // Important: return the modified config
    return config;
  },
};
```

This way you don't need the custom fix on top of all of your script files.

**Comment by SnidelyWhiplash** [comment]
Thanks @fapdash I'll try it out 👍
