### ISSUE TITLE
Background script injection override fails auto-reload when using html page

### ISSUE THREAD

**Issue by SITZ** [webextension-toolbox/webextension-toolbox#308]
## Expected Behavior

`webextension-toolbox/client.js` should be injected in background.html page or the page should be loaded automatically by using relevant script (if both modes for background as indeed going to be supported?)

## Current Behavior

`webextension-toolbox/client.js` directly gets injected into manifest.json even when using html page for background

## Steps to Reproduce (for bugs)

1. Run in dev mode `webextension-toolbox dev chrome `
2. Make any change to your chrome extension
3. Spot the error by Manually reload unpacked chrome extension to see the error
![Screenshot 2020-07-04 at 09 55 11](https://user-images.githubusercontent.com/356043/86509064-779a9000-bde5-11ea-9956-78c46d3bb226.png)
4. Spot the error reason in `dist/chrome/manifest.json` file
```
  "background": {
    "page": "pages/background.html",
    "persistent": false,
    "scripts": [
      "webextension-toolbox/client.js"
    ]
  },
```

## Context

Chrome extension dev references:
- https://developer.chrome.com/extensions/background_pages
- https://developer.chrome.com/extensions/background_migration

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | 3.0.0 |
| node                    | v12.18.1 |
| OS                      | macOS Catalina, Version: 10.15.5 (19F101) |
| browser                 | Google Chrome, Version: 83.0.4103.116 (Official Build) (64-bit) |

**Comment by kensplanet** [comment]
The best solution here would be to detect if `background.page` and if it does, inject `webextension-toolbox/client.js` in background.html instead of adding it in background.scripts.

**Comment by tm1000** [comment]
This is completed in 5.0.0
