### ISSUE TITLE
npm audit reports a lot of issues

### ISSUE THREAD

**Issue by here-nerd** [webextension-toolbox/webextension-toolbox#309]
One of the reported issues is a Cross-Site Scripting on serialize-javascript. 
I am willing to fix, test and submit a pullrequest. Please let me know if you find it important enough to do. I am asking because I have not seen a lot of activities for a long time. It's a pity for a good project like this for being discontinued. I just want to help.

**Comment by pbek** [comment]
I've that alert on my radar too for a long time: https://github.com/qownnotes/web-companion/network/alert/package-lock.json/serialize-javascript/closed 😅

**Comment by here-nerd** [comment]
@pbek, thank you for your reply. Somehow, I cannot open your link. It appears not found (404).

**Comment by pbek** [comment]
Ah, seems like only I can access them in my repo.

![image](https://user-images.githubusercontent.com/1798101/95597969-a319c000-0a4f-11eb-9e45-0076c9c28ef5.png)

**Comment by here-nerd** [comment]
@pbek thanks for the information. 
I can see that the fix of this issue has already been merged to master [here](https://github.com/webextension-toolbox/webextension-toolbox/commit/65c0f1ca977b68db3927ea9b013bf9cf8bac2dc7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519). Can anyone help? How to release a new version?

**Comment by here-nerd** [comment]
For now, I just took the commit that copy-webpack-plugin is bumped to ^5.0.0. It seems to help me.

npm install https://github.com/webextension-toolbox/webextension-toolbox.git#65c0f1ca977b68db3927ea9b013bf9cf8bac2dc7 --save-dev

**Comment by balcsida** [comment]
Hi folks,

I'm sorry for not responding earlier to this (or any other issues, for that matter). I was and still bloated by work every day and on my weekends, I usually just try to rest out the weekly hustle.
I'll check the dependency updates today and try to release an updated version today, if possible.

Thanks for your patience! 🙇

**Comment by pbek** [comment]
Awesome, thank you, @balcsida! 🥳

**Comment by balcsida** [comment]
Despite my best effort, I couldn't finish upgrading the webpack plugin dependency, therefore no new releases today. Sorry to disappoint.

**Comment by pbek** [comment]
Next time then. 😁

**Comment by here-nerd** [comment]
> Despite my best effort, I couldn't finish upgrading the webpack plugin dependency, therefore no new releases today. Sorry to disappoint.

@balcsida Thank you already.. sincerely appreciate it.

**Comment by balcsida** [comment]
It seems that I was able to release a new version of [webpack-webextension-plugin](https://github.com/webextension-toolbox/webpack-webextension-plugin), but now I'm struggling with the upgrade from Webpack v4 to v5.

**Comment by pbek** [comment]
Great new, thank you so far! 🥳

**Comment by pbek** [comment]
Hi, @balcsida. Any news on maybe releasing a new version of https://www.npmjs.com/package/webextension-toolbox with all those dependency fixes you included already?

**Comment by balcsida** [comment]
Hi folks,
I know that I let you down many times, but I'm like inches away from releasing a new version.
Thank you so much for bearing with me! 🙇

**Comment by pbek** [comment]
Yay, I can't wait to test it! 😁 🎉

**Comment by balcsida** [comment]
After 3 years, I've released [v4.0.0](https://github.com/webextension-toolbox/webextension-toolbox/releases/tag/v4.0.0) (and v4.0.1 shortly after that 😅).
Please test it and open a new issue if anything is broken.

**Comment by pbek** [comment]
Is there a migration path from v3 to v4? I get a lot of errors when doing `webextension-toolbox dev chrome` for https://github.com/qownnotes/web-companion/ with webextension-toolbox 4.0.1:

```
webpack-webextension-plugin listens on ws://127.0.0.1:35729
(node:736136) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
TypeError: Cannot read property 'entries' of undefined
    at WebextensionPlugin.extractChangedFiles (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack-webextension-plugin/index.js:245:57)
    at WebextensionPlugin.reloadExtensions (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack-webextension-plugin/index.js:225:31)
    at WebextensionPlugin.done (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack-webextension-plugin/index.js:98:10)
    at Hook.eval [as callAsync] (eval at create (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:36:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack/lib/Watching.js:260:28)
    at /home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack/lib/Watching.js:183:21
    at Compiler.emitRecords (/home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack/lib/Compiler.js:864:39)
    at /home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack/lib/Watching.js:161:22
    at /home/omega/Code/_internal/qownnotes-web-companion/node_modules/webpack/lib/Compiler.js:846:14
```

**Comment by pbek** [comment]
And is the `webextension-toolbox-config.js` still used for adapting the settings? It doesn't seem to get loaded (no errors are thrown from there).

**Comment by balcsida** [comment]
Hmm, I didn't encounter that issue, let me check that on my side

**Comment by pbek** [comment]
Should I open a new issue?

**Comment by balcsida** [comment]
It should be fixed now, no need for separate issue 😅

**Comment by balcsida** [comment]
Hi @pbek,

That is... Really shameful of me, my apologies. I tried to test to my best effort, but I didn't run into these issues.
The latter one was reported on #489 as well, I'll take a look at these at Sunday at earliest.

**Comment by pbek** [comment]
Thank you, I'll subscribe that issue too then.

**Comment by pbek** [comment]
> And is the webextension-toolbox-config.js still used for adapting the settings? It doesn't seem to get loaded (no errors are thrown from there).

@balcsidam, I found out that it now needs to placed in the `app` folder instead of the root folder!

**Comment by pbek** [comment]
> I found out that it now needs to placed in the app folder instead of the root folder!

But projects don't seem to build any more with it, see https://github.com/webextension-toolbox/webextension-toolbox/issues/499

**Comment by balcsida** [comment]
Thanks @pbek for reporting it!
As the originally reported issue is no longer present, I'll mark this as Closed to reduce the noise.
