### ISSUE TITLE
Customizing webpack config problem on Windows

### ISSUE THREAD

**Issue by JimMorrison723** [webextension-toolbox/webextension-toolbox#31]
## Expected Behavior
When i want to extend  usage of Webpack by creating `webextension-toolbox.js`, it should just work.

## Current Behavior
I add `webextension-toolbox.js`, paste code from readme, and add jquery plugin, i got Windows Srcript Host errors all the time. simetimes 1:1, by default it gives error to `dev, vendor`, it expects `:`

## Steps to Reproduce (for bugs)

1. generate extension via generator
2. create `webextension-toolbox.js`
3. yarn add jquery
4. add code:
```
module.exports = {
  webpack: (config, { dev, vendor }) => {
    // Perform customizations to webpack config
	config.plugins.push(
	  new webpack.ProvidePlugin({
		  $: 'jquery',
		  jQuery: 'jquery'
	  })
	)
    // Important: return the modified config
    return config
  }
}
```
Tried different ways for module export, no luck.
## Context

Parts of my extension containes jquery, that's why i need it.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |  1.0.4 |
| node                    |    10.1.0 |
| OS                      |    W10 |
| browser                 |         |
| etc                     |         |

**Comment by bboydflo** [comment]
@HaNdTriX I posted a similar issue on the generator repo. Not sure what's wrong. I am also on Windows. will try the same later, on a mac

**Comment by Linard11** [comment]
I also stumbled upon this problem but I quickly found out through a google search that this is a problem of Windows if no **default program for .js** files is set. Set it to your IDE or text editor and it should not throw this error anymore.

Only slight problem: Even though it will not throw an error, if a webextension-toolbox.js file is present in the root folder, the building will exit without starting webpack; generating no files. I'll open a seperate issue for this.

**Comment by JimMorrison723** [comment]
It's working now. All i got after that, was a `ReferenceError: webpack is not defined`, but it can be easily solved. Made a pull request (#33), so in the future developers don't have to worry about that either.

Next, i'll look into `webpack-webextension-plugin`. For me, seems like after the first reload it is losing connection (Inspecting background page, only the generated background page is available after reloading the first time.) (Win10, Chrome 67.0.3396.56).
You guys (@bboydflo @Linard11) only had problem with extending webpack config, and everything else is working fine?

**Comment by bboydflo** [comment]
It does work on a mac, the issue appears only on windows for me.

**Comment by Linard11** [comment]
@JimMorrison723 @bboydflo requiring weback did not work for me. Still the same problem (see #32)

**Comment by balcsida** [comment]
Hey @JimMorrison723,

Could you please try with cloning/pulling changes from this repo and `npm link` to your project?

Thank you in advance!

**Comment by Linard11** [comment]
https://github.com/webextension-tools/webextension-toolbox/pull/37 should fix this issue

**Comment by balcsida** [comment]
I've tried and as @Linard11 mentioned, #37 fixed this issue.
Note: I had to install locally or link webpack to make this work. I got `Cannot find module 'webpack'` error without doing this.

**Comment by JimMorrison723** [comment]
Looks like issues solved.
