### ISSUE TITLE
question: next release?

### ISSUE THREAD

**Issue by bboydflo** [webextension-toolbox/webextension-toolbox#38]
## Expected Behavior
Maybe it's time for a new release?

## Current Behavior
Current release doesn't allow for configurable webpack config, but that has been fixed in the meantime #31 and #37 

## Context
I want to use the latest version to be able to config webpack further

## Your Environment
OS: windows 10
webextension-toolbox: 1.0.5
node: 8.9.4

**Comment by Linard11** [comment]
In the meantime you can already use the latest version by cloning the repo and npm/yarn link it to your project (note that yarn currently has issues with installing dependencies of linked packages: yarnpkg/yarn#2914)

**Comment by bboydflo** [comment]
of course 👍

**Comment by balcsida** [comment]
Hi,

Only @HaNdTriX has access to the NPM side of webextension-toolbox, so we will have to wait.

**Comment by HaNdTriX** [comment]
Thank you guys for your awesome job!
Sorry that I was letting you wait. In order to improve our release cycles I'll grant @balcsida npm publish rights. 

In addition to that I just released Version 1.1.1

https://www.npmjs.com/package/webextension-toolbox/v/1.1.1
