### ISSUE TITLE
Manifest file missing in the generated packages

### ISSUE THREAD

**Issue by gautamkrishnar** [webextension-toolbox/webextension-toolbox#484]
## Expected Behavior
Manifest file should be in the zip packages

## Current Behavior
There is no Manifest file in the generated packages/* packages while running ` webextension-toolbox <vendor>`

## Steps to Reproduce (for bugs)
1. Init extension using https://github.com/webextension-toolbox/generator-web-extension
2. Run `npm run build <vendor>`

## Context
I cant submit the built packages to store due to this.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |     4.0.1    |
| node                    |    v14.15.4     |
| OS                      |    Macos 11.4     |
| browser                 |    All browsers     |

**Comment by gautamkrishnar** [comment]
Source code: https://github.com/gautamkrishnar/refined-github-feeds

**Comment by tm1000** [comment]
This seems to be working fine?

**Comment by gautamkrishnar** [comment]
yes, it is working now. Thanks for closing.
