### ISSUE TITLE
`@babel/preset-env` Ignores Project Browserslist Config for `targets`

### ISSUE THREAD

**Issue by rthaut** [webextension-toolbox/webextension-toolbox#495]
## Expected Behavior
When using a valid browserslist config (ex: in package.json), the `@babel/preset-env` plugin for `babel-loader` should be targeting the browser(s)/vendor(s) specified in the config if no browser/vendor version is explicitly defined (via the `-v`/`--vendorVersion` flag).

## Current Behavior
The `@babel/preset-env` plugin for `babel-loader` ignores the browserslist config and instead is configured to use the latest known/released version of the target browser/vendor.

## Steps to Reproduce (for bugs)
1. Add a valid browserslist config to the example extension's package.json:
```json
"browserslist": [
  "chrome >= 17",
  "edge >= 15",
  "firefox >= 52",
  "opera >= 15"
]
```

2. Run the `build` script for chrome with no version: `webextension-toolbox build chrome` and copy/backup the generated `background.js` file
3. Run the `build` script for chrome version 17: `webextension-toolbox build chrome -v 17` and copy/backup the generated `background.js` file again
4. Run the `build` script for chrome version 91: `webextension-toolbox build chrome -v 91` and copy/backup the generated `background.js` file a third time
5. Note that the generated script when no version was specified (step 2) and when version 91 was specified (step 4) are the same (assuming Chrome 91 is still the latest release), indicating the browserslist config was not used in step 2
6. Note that the generated script for version 17 (step 3) has additional polyfills added at the top of the file compared to the other generated versions, indicating it was compiled correctly for Chrome 17

## Context
Defining the supported browsers in a browserslist config is the standard way of ensuring compatibility, but the toolbox currently ignores that config. Furthermore, the toolbox defaults to the "latest" release of each browser, which is not a good practice. If, for example Chrome 17 has all of the extension APIs needed for your extension to run, then you could/should be supporting Chrome 17+, not Chrome 91+.

I have created 2 PRs that solve this problem:
* #496, which is not backwards compatible, but is a simpler solution (and I think matches the intent of `@babel/preset-env` better)
* #497, which is backwards compatible, but is a more complex solution

It is important to note that only one of these PRs should be used (not both). I also understand if you want to handle this problem differently and not use either of the PRs.

**Comment by tm1000** [comment]
Merging #143 removed the presets file. So this is either not needed or out of date.
