### ISSUE TITLE
Localization keys are not replaced with strings

### ISSUE THREAD

**Issue by raphaelmenges** [webextension-toolbox/webextension-toolbox#539]
Thank you for the toolbox! Perhaps I have a misunderstanding about its functionality in regard to localization, yet, at least clarification in the documentation might be added.

## Expected Behavior
I would expect the the strings `"__MSG_<key>__"`, e.g., as used in the `manifest.json` in the "bookmark-it" example, to be replaced with the localized strings as defined in `app/_locales/en/messages.json`.

## Current Behavior
The `"__MSG_<key>__"` remain untouched from the build process.

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/webextension-toolbox/webextension-toolbox.git`
2. `cd webextension-toolbox/examples/bookmark-it`
3. `npm install`
4. `npm run-script dev firefox`
5. Inspect `../dist/firefox/manifest.json`

## Your Environment
| Tech                                 | Version |
|-------------------------|---------|
| webextension-toolbox    | 4.0.3 |
| node                                 | 14.17.0 |
| OS                                    | macOS Big Sur |
| browser                           | Mozilla Firefox |

**Comment by gautamkrishnar** [comment]
@raphaelmenges this is expected, most browsers support keys that way 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization
https://developer.chrome.com/docs/extensions/reference/i18n/

**Comment by raphaelmenges** [comment]
Ah! I did not know about this, thank you very much @gautamkrishnar. I will close the issue :)
