### ISSUE TITLE
Should we disable minification?

### ISSUE THREAD

**Issue by HaNdTriX** [webextension-toolbox/webextension-toolbox#57]
### Problem

Some webstores doesn't like it, when extension code is minified.
This makes their review more complex.

### Possible solutions

A. Disable minification
C. Enable minification (everything stays the same)
B. Add an cli flag to leave it up to the user (default will be disabled)
D. Add an cli flag to leave it up to the user (default will be enabled)

### Related docs

https://webpack.js.org/configuration/optimization/

### Open questions

Does tree shaking and dead code elimination still work if minification is disabled? If not can we enable it somehow?

What do you think?

**Comment by bboydflo** [comment]
if that's implemented would it be possible to enable minification again?

**Comment by HaNdTriX** [comment]
@bboydflo in solution B & D yes.

So far I know dead code elimination will be disabled as well. This might suck a projects like react, that depend heavily on  dead code elimination.

**Comment by bboydflo** [comment]
👍 for B or D in this order.

**Comment by balcsida** [comment]
I've checked and it seems that AMO allows you to upload the un-minified version of your code separately for the manual review.
What if we generate two seperate package on `webextension-toolbox build firefox`, one with minified and dead code elimination, and one without it?

**Comment by JimMorrison723** [comment]
I'd say go with option D.
No need to complicate things (and build a not minified version with cli flag is fine)

**Comment by bboydflo** [comment]
I think this needs to be added asap. Please read the official blog: https://blog.chromium.org/2018/10/trustworthy-chrome-extensions-by-default.html where it among others says that minified source code is allowed but it is not allowed to mangle name variables and methods.

**Comment by balcsida** [comment]
Hi @bboydflo,

Thanks for bringing my attention to this and apologies for not reacting earlier on your comment.
Nowadays, I have lots of things on my plate (higher load during work, plenty of extra projects, ~3-4 hours of sleep), so I cannot guarantee anything regarding this yet.
Anyway, I added the major priority flag to indicate the importance of this.

**Comment by balcsida** [comment]
Started working on this

**Comment by balcsida** [comment]
Hi everyone,

Thanks for your kind patience.

I made some progress on this case today, now we have a command line argument `--no-minimize`/`-m` for the build command, which disables Webpack minimize.
I manually tested it and it works as expected. Just need to add some test cases and we are good to go.

I've also discovered a bug while working on this issue.
