### ISSUE TITLE
--autoReload flag not working properly

### ISSUE THREAD

**Issue by QtFuta** [webextension-toolbox/webextension-toolbox#578]
## Expected Behavior
When sending `--autoReload false` the extension should not try to connect to the Web plugin.  

In here is missing `autoreload: arguments[0].autoReload,` or similar
https://github.com/webextension-toolbox/webextension-toolbox/blob/c8e99559585005df2fff42bfe7e8737ab22d4052/src/webpack-config.js#L174-L183

Commander, the library used for the CLI, doesn't work very well with booleans, it always returns a string when the user types something like `--autoReload false`.  
This needs to be changed to `autoReload: options.autoReload === "true",`
https://github.com/webextension-toolbox/webextension-toolbox/blob/c8e99559585005df2fff42bfe7e8737ab22d4052/bin/webextension-toolbox#L28

## Current Behavior
The flag is ignored and it always injects the auto-connect code and creates the server.  
You can check the extension console for the logs about trying to reconnect.  

## Steps to Reproduce (for bugs)
`webextension-toolbox dev --autoReload false <vendor>`

## Your Environment
Firefox.
Windows.
npm 6.13.4

**Comment by tm1000** [comment]
Thanks!
