### ISSUE TITLE
Incognito manifest key "split" is incorrectly blocked by the web extension toolbox at the build time.

### ISSUE THREAD

**Issue by here-nerd** [webextension-toolbox/webextension-toolbox#722]
## Expected Behavior

- Add "incognito": "split" in the manifest.json (mv3). For more information, see https://developer.chrome.com/docs/extensions/mv3/manifest/incognito/
- run `npm start` -- the dev build should works fine.

## Current Behavior

- webpack compiled with 1 error
```
.incognito should be equal to one of the allowed values
{
  "keyword": "enum",
  "dataPath": ".incognito",
  "schemaPath": "#/properties/incognito/enum",
  "params": {
    "allowedValues": [
      "not_allowed",
      "spanning"
    ]
  },
  "message": "should be equal to one of the allowed values"
}
```

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |    5.2.2     |
| node                    |         |
| OS                      |         |
| browser                 |    Chrome Version 110 (x86_64)     |
| etc                     |         |

**Comment by here-nerd** [comment]
I will create a PR. Please assign to me.

**Comment by tm1000** [comment]
Fixed in https://github.com/webextension-toolbox/webpack-webextension-plugin/pull/376

(6.0.)
