### ISSUE TITLE
digital envelope routines::unsupported

### ISSUE THREAD

**Issue by KnightYoshi** [webextension-toolbox/webextension-toolbox#755]
## Expected Behavior
Starting a new project from scratch following the [yeoman generator](https://github.com/webextension-toolbox/generator-web-extension) setup and building it via `npm run dev chrome` works and creates a usable extension

## Current Behavior
After creating a new webextension project following the yoeman generator steps, when trying to build the extension it results in an error before the build completes.

```
webpack-webextension-plugin listens on ws://localhost:35729
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
```

## Steps to Reproduce (for bugs)
Committed it as is at the point of it breaking while building
https://github.com/KnightYoshi/webextension-toolbox-test

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | @webextension-toolbox/webextension-toolbox@6.0.0 |
| node                    | v19.8.1 |
| OS                      | macOS 13.3.1 (a) |
| browser                 | Chrome 113.0.5672.92 |
| etc                     |         |

**Comment by tm1000** [comment]
This error is in `node:internal` and is therefore out of the scope of this library.

Checkout: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
