### ISSUE TITLE
web_accessible_resources ignore js file

### ISSUE THREAD

**Issue by ViZiD** [webextension-toolbox/webextension-toolbox#793]
## Expected Behavior
Add js files defined in web_accessible_resources to the build without minification

## Current Behavior
Right now toolbox just ignores all js files without adding them to the build

## Steps to Reproduce (for bugs)

define any js file in web_accessible_resources

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |   @webextension-toolbox/webextension-toolbox@6.1.0      | 
| node                    |   v19.9.0      |
| OS                      |     Linux    |
| browser                 |    Google Chrome 115.0.5790.110      |
| etc                     |         |

**Comment by tm1000** [comment]
This is resolved in: https://github.com/webextension-toolbox/webextension-toolbox/pull/832
