### ISSUE TITLE
Reloader connection fails with manifest V3

### ISSUE THREAD

**Issue by jokru** [webextension-toolbox/webextension-toolbox#817]
## Expected Behavior

The extension should connect to the autoreloader server and reload the extension when changes are detected.

## Current Behavior

Connection fails.
Firefox console prints:
```
Content-Security-Policy: Upgrading unsafe request 'ws://localhost:35729/' to use 'wss'
(error sign, with tooltip "Blocked by DevTools") GET  wss://localhost:35729/
Connecting to wss://localhost:35729/ failed.
webpack-webextension-plugin: Connection error.
webpack-webextension-plugin: Connection lost. Reconnecting in 3s'
```
And this repeats, even though the reload-server is definitely online.

## Steps to Reproduce (for bugs)
1. Run `yo web-extension` with some values
2. Run `webextension-toolbox dev firefox`
3. Connection works
4. Change manifest version to 3
5. Run `webextension-toolbox dev firefox`
6. Connection fails as above

## Context

Very annoying to constantly manually reload extension

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | 6.1.0 |
| node                    | v18.14.2 |
| OS                      | win10 |
| browser                 | firefox |

Sorry if it's just my stupidity, but I can't seem to get it to work.

**Comment by tm1000** [comment]
Firefox is trying to upgrade the websocket connection to secure websocket. Thats not possible without a valid certificate which you can't get from an ip address.

Seems like this is a firefox bug not a bug in this package

**Comment by tm1000** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests

Actually it's whatever website you are running that one/

**Comment by jokru** [comment]
> See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests
> 
> Actually it's whatever website you are running that on

There is no website, it's the template generated by the yo generator?

**Comment by tm1000** [comment]
Your browser is forcefully upgrading the connection from ws to wss.

**Comment by jokru** [comment]
But why does manifest version affect this behaviour? I also can't seem to get chrome to work with the reload.

**Comment by tm1000** [comment]
I don't have an answer for you. Unfortunately it's nothing to do with this library itself, the error is coming from the browser:

```Content-Security-Policy: Upgrading unsafe request 'ws://localhost:35729/' to use 'wss'```
