### ISSUE TITLE
Extension autoreload is broken on Chrome

### ISSUE THREAD

**Issue by balcsida** [webextension-toolbox/webextension-toolbox#82]
## Expected Behavior
On file change, the browser should reload the extension and the current page

## Current Behavior
On file change, the browser window is reloaded, but you have to manually reload your extension

**Comment by balcsida** [comment]
This was probably caused by WSL for me, will close this now

**Comment by balcsida** [comment]
Note myself:

https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/reload

**Comment by tm1000** [comment]
https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader

is archived in favor of

https://github.com/rubenspgcavalcante/webpack-extension-reloader

**Comment by tm1000** [comment]
[rubenspgcavalcante/webpack-extension-reloader](https://github.com/rubenspgcavalcante/webpack-extension-reloader)

Is abandonware as well..... ~sigh~

**Comment by j1mie** [comment]
Hey @tm1000 this repo appears to be maintained: https://github.com/SimplifyJobs/webpack-ext-reloader

Do you have any suggestions for workarounds in the meantime?

Awesome work on v5 by the way!

**Comment by j1mie** [comment]
@tm1000 it doesn't appear to reload the browser for me when I make changes, or to log anything in the service working (on Chrome, Manifest V3, with React). I can try this on a fresh project and see if it isn't something to do with my own setup.

**Comment by tm1000** [comment]
@j1mie if you have time to see if it works on a fresh repo that would be great because then you could send me that repo and I can investigate. 

As for me I'm using a service worker in my company's extension and I see the logging so I know it's working. But that's "on my machine"

**Comment by j1mie** [comment]
@tm1000 created a repo here https://github.com/j1mie/test_extension

Doesn't refresh the browser when saving... but could also be a my-machine problem!

**Comment by tm1000** [comment]
@j1mie thanks! I'll look at it next week

**Comment by j1mie** [comment]
@tm1000 Hi there, wondering if you had a chance to review? Thanks!

**Comment by tm1000** [comment]
@j1mie I identified the issue. See https://github.com/webextension-toolbox/webpack-webextension-plugin/issues/204
