### ISSUE TITLE
DEV environment is not properly set

### ISSUE THREAD

**Issue by 3n9** [webextension-toolbox/webextension-toolbox#882]
## Expected Behavior

1. To have ```process.env.NODE_ENV``` set to ```development```.
2. To have ```dev``` variable set in ```webextension-toolbox-config.js```

## Current Behavior
1. ```process.env.NODE_ENV``` is always set to ```production```
2. ```dev``` variable in ```webextension-toolbox-config.js``` is always undefined

## Steps to Reproduce (for bugs)
1. clone [https://github.com/webextension-toolbox/js-extension-template](https://github.com/webextension-toolbox/js-extension-template)
3. run ```npm install```
4. add ```console.log(process.env.NODE_ENV);``` to the bottom of ```app/background.js```
5. create ```webextension-toolbox-config.js``` with the following contents:

```
module.exports = {
  webpack: (config, { dev, vendor }) => {
    // Perform customizations to webpack config
    console.log("dev: ", dev);

    // Important: return the modified config
    return config;
  },
};
```

6. update ```package.json``` run script ```webextension-toolbox dev --config webextension-toolbox.config.js```

## Context

1. When running ```npm run dev chrome``` script provides following output:
```
Using Babel loader to compile
dev:  undefined
```

2. After dev build step, last lines of ```dist/chrome/background.js``` looks like this:
```
console.log("production");
}();
/******/ })()
;
```

**Comment by yamadashy** [comment]
Hi,

I encountered an issue with the `process.env.NODE_ENV` always being set to `production` and the `dev` variable in `webextension-toolbox-config.js` always being `undefined`.

Upon investigating, I noticed that the `dev: true` setting was removed in this commit: [850f6dd](https://github.com/webextension-toolbox/webextension-toolbox/commit/850f6dd17ff2ae3a059834337d9373baf8ff6a07#diff-220e508188c117ad32df9748c55ec498955b6c867443133d67d15cc2b0d805f1L12).

I believe adding `dev: true` back into the `compile()` function in `dev.ts` might resolve the issue. I tested this locally and it seems to work as expected.

Could you please confirm if this is the correct approach or suggest any other possible solutions?

Thank you for your assistance.

Best regards,  
Kazuki

**Comment by tm1000** [comment]
changes have been committed that should fix this
