### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by balcsida** [webextension-toolbox/webextension-toolbox#92]
Hi everyone,

As Babel 7 stable is out, I think it is time to release a new version of WebExtension Toolbox.
@HaNdTriX was kind enough to provide me an npm publish access but I never ever released anything before. He recommended me to use sindresorhus/np for the release, but I'm still figuring out whether should I bump the minor or the major version (to 2.0.0).

Could you please help me out in this matter?

I am also opening this ticket to push me to make this happen and not to procrastinate anymore on it.

**Comment by HaNdTriX** [comment]
I already release 2.0.0 on Sep 10, 2018. 😉

https://github.com/webextension-toolbox/webextension-toolbox/commits/master

Since we had breaking changes it was a 2.0.0 Release.

More on choosing the right version at: https://semver.org/

**Comment by balcsida** [comment]
Then I was thinking right, thanks for the confirmation.
I checked that documentation but I feared that I would break something by bumping this much.
