### ISSUE TITLE
typescript (.ts) entry point support

### ISSUE THREAD

**Issue by bboydflo** [webextension-toolbox/webextension-toolbox#93]
Hi, 

I would like to use typescript together with `webextension-generator/webextension-toolbox`. I have tried to import a typescript file and works fine, but I cannot provide a typescript file as an entry point.

## Expected Behavior
A typescript file e.g. `main.ts` (found in `./app/scripts/main.ts`) should be a compiled to `./dist/chrome/scripts/popup.js`

It would be nice to support typescript files as entry points.

## Current Behavior
A typescript file from `app/scripts/main.ts` cannot be used as an entry point because won't get compiled to a `.js` file.

## Steps to Reproduce (for bugs)
1. add main.ts to scripts folder
2. npm run dev chrome
3. expect `dist/chrome/scripts/main.js`

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    | 2.0        |
| node                    | 10.10.0        |
| OS                      | ubuntu-18.04        |
| browser                 | chrome        |
| etc                     |         |

**Comment by bboydflo** [comment]
I fixed this by overwriting `config.entry`. I've got some inspiration from the actual source code. I am not sure that this lib should support typescript out of the box, mainly because there are multiple loaders one could use. 

Closing for now

**Comment by balcsida** [comment]
Hi @bboydflo,

Could you please share the code and configuration you have used?
This should be a useful Readme/Wiki entry for others.

If it is not a problem, I reopened this issue and added the "documentation" label to it.

Kind regards,
balcsida

**Comment by bboydflo** [comment]
@balcsida Something like this should work: I have removed some parts from my original code.

inside `webextension-toolbox-config.js`

```js
const { resolve } = require('path')
const GlobEntriesPlugin = require('webpack-watched-glob-entries-plugin')

module.exports = {
  webpack: (config, { dev, vendor }) => {
    // Add typescript loader. supports .ts and .tsx files as entry points
    config.resolve.extensions.push('ts')
    config.resolve.extensions.push('tsx')
    config.entry = GlobEntriesPlugin.getEntries(
      [
        resolve('app', '*.{js,mjs,jsx,ts,tsx}'),
        resolve('app', '?(scripts)/*.{js,mjs,jsx,ts,tsx}')
      ]
    )
    config.module.rules.push({
      test: /\.tsx?$/,
      loader: 'ts-loader'
    })

    // Important: return the modified config
    return config
  }
}
```

**Comment by balcsida** [comment]
Thanks for your quick reply!
I will add this to the documentation and keep this ticket opened until.

**Comment by bboydflo** [comment]
I have noticed that my `.ts` files get copied over dist folder so I changed my `webextension-toolbox-config.js` a bit. I also had to add support for `tslint` so I added some more config like below. I hope it helps someone.

```js
const { resolve } = require('path')
const GlobEntriesPlugin = require('webpack-watched-glob-entries-plugin')

module.exports = {
  webpack: (config, { dev, vendor }) => {
    // Add typescript loader. supports .ts and .tsx files as entry points
    config.resolve.extensions.push('ts')
    config.resolve.extensions.push('tsx')
    config.entry = GlobEntriesPlugin.getEntries(
      [
        resolve('app', '*.{js,mjs,jsx,ts,tsx}'),
        resolve('app', '?(scripts)/*.{js,mjs,jsx,ts,tsx}')
      ]
    )
    /* // add tslint support
    config.module.rules.push({
      test: /\.tsx?$/,
      enforce: 'pre',
      use: [{
        loader: 'tslint-loader',
        options: {
          tsConfigFile: 'tsconfig.json',
          emitErrors: true
        }
      }]
    }) */

    config.module.rules.push({
      test: /\.tsx?$/,
      loader: 'ts-loader'
    })

    // Important: return the modified config
    return config
  },
  copyIgnore: [ '**/*.js', '**/*.json', '**/*.ts', '**/*.tsx' ]
}
```
To add support for `tslint` using `tslint-loader` install `tslint-loader` as a dev dependency (`npm i -D tslint-loader` and uncomment `tslint-loader` lines from above

**Comment by thuy-le-ep** [comment]
Is there any way to exclude a folder when compile? E.g. I have 3rd libraries in folder "notCompileScripts" and I want keep them not compile.

## Expected Behavior
A 3rd file e.g. `jquery.js` (found in `./app/notCompileScripts/jquery.js`) should be keep in `./dist/chrome/notCompileScripts/jquery.js`

## Current Behavior
All `.js` file in `notCompileScripts` will be ignored as entry file .

## Steps to Reproduce
Add custom `webextension-toolbox-config.js` file

```javascript
const {
    resolve
} = require('path')
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
    webpack: (config, {
        src,
        target,
        dev,
        vendor
    }) => {
        var target = resolve(target.replace('[vendor]', vendor))
        config.plugins.push(new CopyPlugin([{
            context: resolve(src),
            from: resolve(src, './notCompileScripts/**'),
            to: target
        }]));

        // Important: return the modified config
        return config
    }
}
```
It works OK when run `dev` but when I run `build` it not work. Seem it was zipped before copy
```
√ success webpack compiled in 6s 291ms
Time: 6301ms
Built at: 09/24/2018 4:49:45 PM
                                                Asset       Size  Chunks             Chunk Names
                             icons/star-filled-38.png   1.19 KiB          [emitted]
                                        background.js   89.5 KiB       0  [emitted]  background
                             icons/bookmark-it@2x.png   3.09 KiB          [emitted]
                                        icons/LICENSE  194 bytes          [emitted]
                              icons/star-empty-19.png  556 bytes          [emitted]
                                icons/bookmark-it.png   1.41 KiB          [emitted]
                              icons/star-empty-38.png  959 bytes          [emitted]
                                    content-script.js   89.3 KiB       1  [emitted]  content-script
                             icons/star-filled-19.png  753 bytes          [emitted]
                                        manifest.json  916 bytes          [emitted]
..\..\packages\extension-vs-webpage.v0.0.1.chrome.zip   70.4 KiB          [emitted]
                     notCompileScripts/comm-ext-wp.js   1.86 KiB          [emitted]
                 notCompileScripts/libs/postal.min.js   8.07 KiB          [emitted]
                 notCompileScripts/libs/lodash.min.js   71.5 KiB          [emitted]
```
Is there any way? Or can I edit `copyIgnore` variable to make it work with minimum efforts. Thank you!

## Your Environment
| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |    2.0     |
| node                    |    v10.10.0     |
| OS                      |     Window 10    |
| browser                 |         |
| etc                     |         |

**Comment by bboydflo** [comment]
@thuy-le-ep I have added some sample code above on how to register/overwrite entry points. In my case I needed to overwrite entry points to support `.ts` and `.tsx` files. in your case I think something like this should work:

```js
const { resolve } = require('path')
const GlobEntriesPlugin = require('webpack-watched-glob-entries-plugin')

module.exports = {
  webpack: (config, { dev, vendor }) => {
    config.entry = GlobEntriesPlugin.getEntries(
      [
        resolve('app', '*.{js,mjs,jsx}'),
        resolve('app', '?(scripts)/*.{js,mjs,jsx}')
      ],
      {
          ignore: 'notCompileScripts/*.js'
      }
    )
    // Important: return the modified config
    return config
  }
}

```

**Comment by thuy-le-ep** [comment]
@bboydflo thank you. But it not work. I think `webpack-watched-glob-entries-plugin` to restart the compiler in watch mode, when new files got added or changed.

**Comment by bboydflo** [comment]
@thuy-le-ep do you have any repo to reproduce this?

**Comment by thuy-le-ep** [comment]
@bboydflo update
 `copyIgnore: ['**/!(notCompileScripts)/*.js','**/*.json']`
 can work with case
`notCompileScripts\keepScript.js -> dist\notCompileScripts\keepScript.js`
but not work with case
`notCompileScripts\some-dir\keepScript.js`

Do you have any idea? Thank you

**Comment by bboydflo** [comment]
maybe something like this? 
```js
copyIgnore: ['**/!(notCompileScripts)/**/*.js','**/*.json']
```

**Comment by thuy-le-ep** [comment]
@bboydflo I was tried this but the result same `'**/!(notCompileScripts)/*.js'`

**Comment by bboydflo** [comment]
@thuy-le-ep can you share the whole `webextension-toolbox-config.js` ?

**Comment by thuy-le-ep** [comment]
@bboydflo app structure

```
app
    -- icons
    -- lib
    -- notCompileScripts
        -- some-dir
            -- keep-js-file.js
        -- keep-js-file-2.js
    -- background.js
    -- content.js
    -- manifest.json
webextension-toolbox-config.js
```
and `webextension-toolbox-config.js`

```javascript
module.exports = {
    webpack: (config, {
        dev,
        vendor
    }) => {
        // Important: return the modified config
        return config
    },
    copyIgnore: ['**/!(notCompileScripts)/**/*.js','**/*.json']
}
```
When `dev` or `build`, only the file in folder `notCompileScripts` will to keep without file in sub-folder.
```

-- notCompileScripts                            -- notCompileScripts 
    -- some-dir                                   -- ignored 
        -- keep-js-file.js          ===>             -- ignored 
    -- keep-js-file-2.js                          -- keep-js-file-2.js   
```
But I want keep all files and files in all sub-folders.

**Comment by bboydflo** [comment]
so I revisited your original question
> Is there any way to exclude a folder when compile?

and I think it's still possible since you have access to the original config options you still can tweak them as you wish. I think maybe what you need is this: https://webpack.js.org/configuration/module/#module-noparse maybe something like this:

```js
module.exports = {
    webpack: (config, {
        dev,
        vendor
    }) => {
        config.module.noParse = /notCompileScripts\/some-dir/
        // Important: return the modified config
        return config
    }
}
```

try this and see if it works. maybe you also need to tweak the `'copy-webpack-plugin' config. good luck!

**Comment by thuy-le-ep** [comment]
@bboydflo ok thank you 👍

**Comment by balcsida** [comment]
Raised priority to major. I will document this as soon as possible.

**Comment by yamadashy** [comment]
In `webextension-toolbox` v4, `copyIgnore` has breaking changed on `copy-webpack-plugin >= v6`.
https://github.com/webpack-contrib/copy-webpack-plugin/blob/797a006521521603d5cdf34b1041a59ade07dd25/CHANGELOG.md#600-2020-05-15

I changed `copyIgnore` in this comment's code to this and it worked.
https://github.com/webextension-toolbox/webextension-toolbox/issues/93#issuecomment-422022157
```diff
- copyIgnore: [ '**/*.js', '**/*.json', '**/*.ts', '**/*.tsx' ]
+ copyIgnore: [ path.resolve('**/*.{js,json,ts,tsx}') ]
```
